services:
  website:
    build: .
    image: preethammaiya/website:dev
    volumes:
      - ./blog/resume.pdf:/resume.pdf:ro
    environment:
      - RESUME_FILE=./resume.pdf
  nginx:
    image: "nginx"
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/:/etc/nginx/logs/